#pragma once
#define DEFAULT_VASM_OBJ_EXTENSION ".vasmobj"

#define DEFAULT_INFO_LEVEL 1
#define INFO_LEVEL_MAX 3

#define ERROR_MESSAGE "[ERROR]: "
#define INFO_MESSAGE "[INFO]: "

#define VASM_HEX_FORMAT_STR "v3.0 hex words plain"
#define ONE_INSTRUCTION_PER_LINE_VASM_OBJECT 1
#define BYTES_PER_LINE_VASM_OBJECT 20